#!/usr/bin/env python
import utils.parser as parser
import sys


if len(sys.argv) == 1:
    msg = "Uso:\n   pyemtvlc <Número Parada> <Linea (Opcional)>\n"
    # msg += "   pyemtvlc -s <Número Tarjeta>"
else:
    numParada = sys.argv[1]
    if not numParada.isdigit():
        msg = "No has introducido un número de parada válido."
    else:
        print("Parada: " + numParada)
        msg = parser.next_buses(numParada)

print(msg)
