#!/usr/bin/env python
import sys
from utils.parser import next_buses


def main():
    if len(sys.argv) == 1:
        msg = "Uso:\n   pyemtvlc <Número Parada> <Linea (Opcional)>\n"
        # msg += "   pyemtvlc -s <Número Tarjeta>"
    else:
        numParada = sys.argv[1]
        if not numParada.isdigit():
            msg = "No has introducido un número de parada válido."
        else:
            print("Parada: " + numParada)
            numLinea = ''
            if len(sys.argv) > 2:
                numLinea = numLinea + sys.argv[2]
                numLinea = numLinea.lower()
            msg = next_buses(numParada, numLinea)
    print(msg)


if __name__ == '__main__':
    main()
